# Coolify Configuration File - Producci贸n
# Este archivo es usado por Coolify para desplegar la aplicaci贸n en producci贸n
# Documentaci贸n: https://coolify.io/docs

version: '3.8'

services:
  # Backend API Service (.NET Core)
  api:
    image: ${DOCKER_REGISTRY}/minimarket-api:${VERSION:-latest}
    build:
      context: ./src
      dockerfile: Minimarket.API/Dockerfile
    expose:
      - "5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION_STRING}
      - JwtSettings__SecretKey=${JWT_SECRET_KEY}
      - JwtSettings__Issuer=${JWT_ISSUER:-MinimarketAPI}
      - JwtSettings__Audience=${JWT_AUDIENCE:-MinimarketWeb}
      - EmailSettings__SmtpServer=${SMTP_SERVER:-smtp.gmail.com}
      - EmailSettings__SmtpPort=${SMTP_PORT:-587}
      - EmailSettings__SmtpUser=${SMTP_USER:-minimarket.camucha@gmail.com}
      - EmailSettings__SmtpPassword=${SMTP_PASSWORD:-xzloatedigfqgyxi}
      - EmailSettings__FromEmail=${FROM_EMAIL:-minimarket.camucha@gmail.com}
      - EmailSettings__FromName=${FROM_NAME:-Minimarket Camucha}
      - EmailSettings__ApiKey=${RESEND_API_KEY:-}
      - EmailSettings__ApiUrl=https://api.resend.com/emails
      - BaseUrl=${BASE_URL}
      - FrontendUrl=${FRONTEND_URL}
      - Cors__AllowedOrigins=${CORS_ORIGINS}
      - GoogleOAuth__ClientId=${GOOGLE_CLIENT_ID:-259590059487-5k8bk2sor6r9oa02pojkhj5nrd8c9h2e.apps.googleusercontent.com}
      - GoogleOAuth__ClientSecret=${GOOGLE_CLIENT_SECRET:-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}
      - GoogleOAuth__RedirectUri=${GOOGLE_REDIRECT_URI}
    volumes:
      - uploads:/app/wwwroot/uploads
      - logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  # Frontend Service (Angular + Nginx)
  web:
    image: ${DOCKER_REGISTRY}/minimarket-web:${VERSION:-latest}
    build:
      context: ./minimarket-web
      dockerfile: Dockerfile
      args:
        - API_URL=${API_URL}
    expose:
      - "80"
    depends_on:
      - api
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web-http.rule=Host(`minimarket.edvio.app`)"
      - "traefik.http.routers.web-http.entrypoints=web"
      - "traefik.http.routers.web-http.middlewares=web-to-websecure-redirect"
      - "traefik.http.routers.web.rule=Host(`minimarket.edvio.app`)"
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.routers.web.tls=true"
      - "traefik.http.routers.web.tls.certresolver=letsencrypt"
      - "traefik.http.middlewares.web-to-websecure-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.web-to-websecure-redirect.redirectscheme.permanent=true"
      - "traefik.http.services.web.loadbalancer.server.port=80"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped

volumes:
  uploads:
  logs:
