# Coolify Configuration File
# Este archivo ayuda a Coolify a entender cómo desplegar tu aplicación

version: '3.8'

services:
  # Backend API Service
  api:
    image: ${DOCKER_REGISTRY}/minimarket-api:${VERSION:-latest}
    build:
      context: ./src
      dockerfile: Minimarket.API/Dockerfile
    ports:
      - "${PORT:-8080}:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION_STRING}
      - JwtSettings__SecretKey=${JWT_SECRET_KEY}
      - JwtSettings__Issuer=${JWT_ISSUER:-MinimarketAPI}
      - JwtSettings__Audience=${JWT_AUDIENCE:-MinimarketWeb}
      - EmailSettings__SmtpServer=${SMTP_SERVER}
      - EmailSettings__SmtpPort=${SMTP_PORT:-587}
      - EmailSettings__SmtpUser=${SMTP_USER}
      - EmailSettings__SmtpPassword=${SMTP_PASSWORD}
      - EmailSettings__FromEmail=${FROM_EMAIL}
      - EmailSettings__FromName=${FROM_NAME:-Minimarket Camucha}
      - EmailSettings__ApiKey=${RESEND_API_KEY}
      - BaseUrl=${BASE_URL}
      - FrontendUrl=${FRONTEND_URL}
      - Cors__AllowedOrigins=${CORS_ORIGINS}
    volumes:
      - uploads:/app/wwwroot/uploads
      - logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  # Frontend Service
  web:
    image: ${DOCKER_REGISTRY}/minimarket-web:${VERSION:-latest}
    build:
      context: ./minimarket-web
      dockerfile: Dockerfile
      args:
        - API_URL=${API_URL}
    ports:
      - "${WEB_PORT:-80}:80"
    depends_on:
      - api
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped

volumes:
  uploads:
  logs:

